//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicReply
    {
        public long ID { get; set; }
        public Nullable<long> ForumTopicFK { get; set; }
        public Nullable<long> RepliedBy { get; set; }
        public string ReplyMessage { get; set; }
        public string DateReplied { get; set; }
        public string TimeReplied { get; set; }
    
        public virtual ForumTopic ForumTopic { get; set; }
        public virtual User User { get; set; }
    }
}
