//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EntitiesModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using DataObject.Model;

    public partial class ForumAppDBEntities : DbContext
    {
        public ForumAppDBEntities()
            : base("name=ForumAppDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetMenuRole> AspNetMenuRoles { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<TopicReply> TopicReplies { get; set; }
        public virtual DbSet<ForumTopic> ForumTopics { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<sp_GetForumTopicReply_Result> sp_GetForumTopicReply(Nullable<int> forumTopicFK)
        {
            var forumTopicFKParameter = forumTopicFK.HasValue ?
                new ObjectParameter("ForumTopicFK", forumTopicFK) :
                new ObjectParameter("ForumTopicFK", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetForumTopicReply_Result>("sp_GetForumTopicReply", forumTopicFKParameter);
        }
    
        public virtual ObjectResult<sp_GetForumTopics_Result> sp_GetForumTopics()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetForumTopics_Result>("sp_GetForumTopics");
        }
    }
}
